package com.mohdshayan.habits.domain

val StoicDisciplineQuotes: List<String> = listOf(
    "You become what you do each day, not what you plan to do.",
    "Discipline is choosing what matters most over what feels easy now.",
    "Master the morning, and the day follows your lead.",
    "A calm mind and a consistent action beat intensity every time.",
    "Do the hard thing before your excuses wake up.",
    "Your standards decide your future more than your goals do.",
    "Small repeated effort is stronger than rare motivation.",
    "Self-respect grows from promises kept to yourself.",
    "Comfort postpones growth; discipline delivers it.",
    "You do not rise to intentions, you fall to routines.",
    "Consistency is a decision renewed daily.",
    "Delay the impulse, protect the mission.",
    "The disciplined day is built, not found.",
    "You are free when your habits obey your values.",
    "Progress is quiet, steady, and often uncelebrated.",
    "Train your mind to stay when it wants to run.",
    "A focused hour can redeem a distracted day.",
    "Control the controllable and release the rest.",
    "Character is formed in the repetitions no one sees.",
    "Act with intention, not with mood.",
    "The first victory is getting started without negotiation.",
    "What you repeat, you reinforce.",
    "Discipline is self-care aimed at your future self.",
    "Today’s restraint is tomorrow’s freedom.",
    "Win the next choice, then the next.",
    "Routine is the bridge between values and results.",
    "Keep your word to yourself, especially in private.",
    "Momentum is born from finished basics.",
    "Steady effort outperforms emotional bursts.",
    "Choose principles over impulses.",
    "The mind follows the body into action.",
    "The path gets easier when quitting is not an option.",
    "A disciplined life is a peaceful life.",
    "When motivation fades, structure carries you.",
    "Do not chase intensity; protect consistency."
)
